In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.datasets import load_digits

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

from sklearn.svm import SVC

In [18]:
digits = load_digits()
X = StandardScaler().fit_transform(digits.data)
Y = digits.target

df = pd.DataFrame(X)
df.head(5)

0         1         2         3         4         5         6         7   \
0  0.0 -0.335016 -0.043081  0.274072 -0.664478 -0.844129 -0.409724 -0.125023   
1  0.0 -0.335016 -1.094937  0.038648  0.268751 -0.138020 -0.409724 -0.125023   
2  0.0 -0.335016 -1.094937 -1.844742  0.735366  1.097673 -0.409724 -0.125023   
3  0.0 -0.335016  0.377661  0.744919  0.268751 -0.844129 -0.409724 -0.125023   
4  0.0 -0.335016 -1.094937 -2.551014 -0.197863 -1.020657 -0.409724 -0.125023   

         8         9   ...        54        55        56        57        58  \
0 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596 -0.299081  0.086719   
1 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596 -0.299081 -1.089383   
2 -0.059078 -0.624009  ...  0.259230 -0.209785 -0.023596 -0.299081 -1.089383   
3 -0.059078  1.879691  ...  1.072563 -0.209785 -0.023596 -0.299081  0.282736   
4 -0.059078 -0.624009  ... -0.757436 -0.209785 -0.023596 -0.299081 -1.089383   

         59        60        61        62        63  
0  0.208293 -0.366771 -1.146647 -0.505670 -0.196008  
1 -0.249010  0.849632  0.548561 -0.505670 -0.196008  
2 -2.078218 -0.164037  1.565686  1.695137 -0.196008  
3  0.208293  0.241430  0.379040 -0.505670 -0.196008  
4 -2.306869  0.849632 -0.468564 -0.505670 -0.196008  

[5 rows x 64 columns]

In [19]:
print(df.isna().sum().sum(), df.isnull().sum().sum())

0 0


In [20]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

svm_classifier = SVC(kernel='linear')
svm_classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [21]:
Y_pred = svm_classifier.predict(X_test)

In [22]:
print(metrics.classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        53
           1       0.98      0.98      0.98        50
           2       0.98      1.00      0.99        47
           3       0.96      0.96      0.96        54
           4       1.00      1.00      1.00        60
           5       0.97      0.95      0.96        66
           6       0.98      0.98      0.98        53
           7       1.00      0.98      0.99        55
           8       0.95      0.95      0.95        43
           9       0.97      0.97      0.97        59

    accuracy                           0.98       540
   macro avg       0.98      0.98      0.98       540
weighted avg       0.98      0.98      0.98       540



In [23]:
print(metrics.confusion_matrix(Y_test, Y_pred))

[[53  0  0  0  0  0  0  0  0  0]
 [ 0 49  0  0  0  0  0  0  1  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  1 52  0  1  0  0  0  0]
 [ 0  0  0  0 60  0  0  0  0  0]
 [ 0  0  0  1  0 63  1  0  0  1]
 [ 1  0  0  0  0  0 52  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  1]
 [ 0  1  0  0  0  1  0  0 41  0]
 [ 0  0  0  1  0  0  0  0  1 57]]
